### PR TITLE
Suppress Perl warning on deep recursion; supply own

### PR DESCRIPTION
**Pull request by pdl**
As discussed in #43, this PR suppresses perl's own recursion warnings in the Pegex::Parser package and instead supplies recursion warnings on `match_next`. The class has two new attributes to control this behaviour - one to count the current stack depth, one to set the depth at which the warnings are triggered. The depth may be set to 0, in which case no warnings are given, but by default it is 100, the same as perl's limit.

Usefully, the depth is printed every time a multiple of the soft limit is reached, from which you can tell if the parser is just crossing the line briefly or recursing ever deeper.

### CODE REVIEW

**Comment by ingydotnet** [comment]
I like this a lot. I can't believe I didn't know about the `no warnings` thing.

I don't like adding code to the tight loop. But if we can optimize it away when
we want to, that's good.

I'm thinking of this:

```
use constant PEGEX_RECURSION_CONSTANT => 100;
use Pegex;
```

When the constant is set to zero the code is optimized out. I'm not sure if the
default should be on or off.

**Comment by ingydotnet** [comment]
Applied but heavily modified.

Added 3 new options that can be parser attributes, Pegex::Parser:: globals or
env vars.

See Pegex::Parser doc "Debugging" section.

Cheers!

**Comment by ingydotnet** [comment]
Reopening this until released to CPAN.

**Comment by pdl** [comment]
Thanks. Looking forward to trying it out.

**Comment by perlpunk** [comment]
@pdl CPAN release 0.63 is out

**Pull request closed without merging**
